name: Build lineageOS Kernel
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Init Repo
        run: |
          bash -x ./ci.sh
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testbuild
          path: releases/*.zip
