name: Build lineageOS Kernel
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Init Repo
        run: |
          bash -x ./ci.sh
      - name: upload release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "dev"
          body: ${{ github.event.release.body }}
          prerelease: "true"
          artifacts: "releases/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
