name: Update Submodules
on:
  workflow_dispatch:  # 手动触发
jobs:
  update_submodules:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Change to Repository Root
      run: cd $GITHUB_WORKSPACE

    - name: Run update_submodules.sh
      run: |
        chmod +x update_submodules.sh
        ./update_submodules.sh
